--kasutajad
insert into toidupyramiid.users(email, fullname, birthdate, gender, height, weight, activityLevel, userpassword)
values('risto@palm.ee', 'Risto', '19900921', 1, 198, 110, 1, 'parool1');
insert into toidupyramiid.users(email, fullname, birthdate, gender, height, weight, activityLevel, userpassword)
values('rene@reede.ee', 'Rene', '19940121', 1, 190, 90, 3, 'parool2');
insert into toidupyramiid.users(email, fullname, birthdate, gender, height, weight, activityLevel, userpassword)
values('ellen@turk.ee', 'Ellen Türk', '19880501', 2, 160, 60, 2, 'parool3');

insert into toidupyramiid.users(email, fullname, userpassword)
values('kiki@miki.ee', 'Kiki Miki', 'parool3');


--toidud
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('rukkileib, täisterajahust leib, seemneleib', 30, 'g', 1, '1 viil = 30–50 g. Eelistada seda gruppi järgmistele, Varieerida');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('sepik, täisterasai, karask', 30, 'g', 1, '1 viil = 15–25 g. Eelistada seda gruppi järgmistele, Varieerida');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('peenleib', 30, 'g', 1, '1 viil = ca 40 g. Vähem siit grupist');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('sai', 30, 'g', 1, '1 viil = 15–20 g. Vähem siit grupist');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kukkel', 30, 'g', 1, '1 kukkel ca 50 g. Vähem siit grupist');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('lavaðð', 30, 'g', 1, 'Vähem siit grupist');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('näkileib', 20, 'g', 1, '1 tk = ca 7–20 g. Vähem siit grupist');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('riisi- ja tatraleivake', 20, 'g', 1, '1 tk = 8–10 g. Vähem siit grupist');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kaera-, rukki-, odra-, tatra- või hirsipuder või keedetud teraviljad põhitoidu lisandina', 100, 'g', 2, '1 dl = 100 g. Putrude-lisandite puhul on arvestatud, et need on valmistatud veega ja rasvaineta. Valmistades putru piima ja rasvainega, tuleb juurde arvestada vastavad piima- ja lisatavate rasvade portsjonid. Eelistada täisteraputrusid. Varieerida.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('maisipõhiseid tooteid', 75, 'g', 2, '7–8 spl = 75 g. V.a maisikrõpsud ja maisihelbed');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keedetud riis', 70, 'g', 2, '1 dl = ca 80 g. Eelistada täisteratooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keedetud pastatooted ', 70, 'g', 2, '1 dl = ca 60 g. Eelistada täisteratooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keedetud kinoad ', 70, 'g', 2, '1 dl = ca 80 g. Eelistada täisteratooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keedetud kuskuss', 50, 'g', 2, 'ca 0,5 dl = 50 g ');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('jahu toiduvalmistamisel', 25, 'g', 3, 'ca 1/3 dl ehk ca 2 spl = 25 g');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('maisihelbed ', 20, 'g', 3, '1 dl = 20 g. Eelistada magustamata maisihelbeid ja võimalikult “naturaalset” müslit');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('müsli', 20, 'g', 3, '1 dl = ca 15–35 g. Eelistada magustamata maisihelbeid ja võimalikult “naturaalset” müslit');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kamajahu ', 20, 'g', 3, '2 spl = 20 g. Eelistada teiste teraviljatoodete grupis kama.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keedetud kartul ', 100, 'g', 4, '1 keskmine kartul = ca 80–100 g. Eelistada seda gruppi. Kartulipudru puhul arvestada vajadusel juurde lisatud piim- ja rasvaineportsjonid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keedetud maguskartul ', 70, 'g', 4, '1 keskmine maguskartul = ca 130 g. Eelistada seda gruppi. Kartulipudru puhul arvestada vajadusel juurde lisatud piim- ja rasvaineportsjonid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kartulipuder', 100, 'g', 4, '1 dl = ca 85 g. Eelistada seda gruppi. Kartulipudru puhul arvestada vajadusel juurde lisatud piim- ja rasvaineportsjonid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('friikartulid fritüüris', 100, 'g', 4, '1 dl = ca 50 g. Arvestada 100 g kohta juurde ca 25 g õli (ca 5 tl) ehk 5 portsjonit rasvu. Ära küpseta liialt pruuniks.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('friikartulid ahjus', 100, 'g', 4, '1 dl = ca 50 g. Arvestada 100 g kohta juurde ca 10 g õli (ca 2 tl) ehk 2 portsjonit rasvu.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('prae- ja ahjukartulid (vähese rasvaga)', 100, 'g', 4, '1 dl = ca 65 g. Arvestada 100 g kohta juurde ca 5 g õli (ca 1 tl) ehk 1 portsjon rasvu.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('värsked või kuumtöödeldud kaunviljad', 30, 'g', 5, 'keskmiselt ca ½ dl = 30 g. kaunviljade hulka kuuluvad herned, oad (v.a Türgi oad), läätsed. Nädalas võiks kaunvilju süüa 3–4 portsjonit.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuivatatud kaunviljad', 10, 'g', 5, 'ca 1 spl = 10 g. kaunviljade hulka kuuluvad herned, oad (v.a Türgi oad), läätsed. Nädalas võiks kaunvilju süüa 3–4 portsjonit.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('värsked seened ', 130, 'g', 5, 'ca 4 dl = 130 g. Toidu valmistamisel arvestada vajadusel juurde rasva-hapukoore- vm portsjonid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('Köögiviljasalat mahlaga või kastmeta ', 100, 'g', 5, '1 dl = ca 70–90 g');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('köögiviljasalat õliga ', 100, 'g', 5, '1 dl = ca 70–90 g. Lisaks arvestada 100 g salati kohta ca 5 g (1 tl) ehk 1 portsjon õli.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('köögiviljasalat hapukoore- või majoneeskastmega', 100, 'g', 5, '1 dl = ca 80–100 g. Lisaks arvestada juurde hapukoorest või majoneesist tulevad portsjonid. Kui salat sisaldab midagi peale köögiviljade, siis arvestada lisaks ka nendega (nt kartul, vorst, kala, muna, oliivid vm).');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('köögiviljamahl või letðo', 80, 'g', 5, '1 dl = 100 g. Koguse suurendamine ei kompenseeri köögiviljade kasutamata jätmist.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('köögiviljakonserv (õlita) ', 60, 'g', 5, '1 dl = ca 80–120 g. Eelistada värskeid, sest tegelikult saab 60 grammist konservist kätte vähem toitaineid kui 100 grammist värsketest-kuumtöödeld köögiviljadest.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('Köögiviljakonserv õliga ', 60, 'g', 5, '1 dl = ca 80–120 g. Lisaks arvestada ca 5 g (1 tl) ehk 1 portsjon õli.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('idud, idandatud terad', 20, 'g', 5, 'ca 4 spl = 20 g');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('puuvilja- või marjamahl (v.a mahlajook, nektar)', 100, 'g', 6, '1 dl = 100 g. Eelistada värskeid puuvilju ja marju. Igapäevane mahlajoomine ei kompenseeri värskete puuviljade-marjade kasutamata jätmist. Mahlaga võiks asendada maksimaalselt ühe puuviljaportsjoni päevas.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('puuviljakonserv, -kompott', 100, 'g', 6, '1 dl = 70–100 g. Eelistada värskeid puuvilju-marju. Konserve-kompotte kasutada maksimaalselt mõned portsjonid nädalas. Arvestada 100 g kohta lisaks umbes 10–20 g (2–5 tl) ehk 1–2 portsjonit suhkrut.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuivatatud marjad-puuviljad', 20, 'g', 6, '2 spl = 20 g. Eelistada värskeid puuvilju ja marju. Maksimaalselt 2–3 portsjonit nädalas. Koguse suurendamine ei kompenseeri tavaliste puuviljade-marjade kasutamata jätmist.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('alla 2,5% rasvasisaldusega piim', 250, 'g', 7, '2,5 dl = 250 g. Vedelatest piimatoodetest tuleks eelistada 2,5%-seid tooteid. Kui tervislikel põhjustel ei ole vastu näidustatud, võiks vähemalt ühe portsjoni valida sellest grupist.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('2,5 % rasvasisaldusega piima', 200, 'g', 7, '2 dl = 200 g. Vedelatest piimatoodetest tuleks eelistada 2,5%-seid tooteid. Kui tervislikel põhjustel ei ole vastu näidustatud, võiks vähemalt ühe portsjoni valida sellest grupist.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('üle 2,5% rasvasisaldusega piim', 170, 'g', 7, '1,7 dl = 170 g. Vedelatest piimatoodetest tuleks eelistada 2,5%-seid tooteid. Kui tervislikel põhjustel ei ole vastu näidustatud, võiks vähemalt ühe portsjoni valida sellest grupist.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuni 2,5 % rasvasisaldusega hapupiim, pett, keefir', 220, 'g', 7, 'Vedelatest piimatoodetest tuleks eelistada 2,5%-seid tooteid. Kui tervislikel põhjustel ei ole vastu näidustatud, võiks vähemalt ühe portsjoni valida sellest grupist.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuni 2,5% (k.a) rasvasisaldusega maitsestamata kohupiim või kodujuust', 130, 'g', 8, 'Ülejäänud piimatoodete portsjonid tuleks valida eelistatult siit grupist. Eelistage igast alagrupist madalama rasvasusega tooteid, kuid mitte päris lahjasid. Juustude hulku kuuluvad ka toorjuust, sulatatud juust, hallitusjuust, suitsujuust, kitsejuust, mozzarella.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('2,51–5% rasvasisaldusega maitsestamata kohupiim või kodujuust', 120, 'g', 8, 'Ülejäänud piimatoodete portsjonid tuleks valida eelistatult siit grupist. Eelistage igast alagrupist madalama rasvasusega tooteid, kuid mitte päris lahjasid. Juustude hulku kuuluvad ka toorjuust, sulatatud juust, hallitusjuust, suitsujuust, kitsejuust, mozzarella.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('üle 5% rasvasisaldusega maitsestamata kohupiim või kodujuust', 80, 'g', 8, 'Ülejäänud piimatoodete portsjonid tuleks valida eelistatult siit grupist. Eelistage igast alagrupist madalama rasvasusega tooteid, kuid mitte päris lahjasid. Juustude hulku kuuluvad ka toorjuust, sulatatud juust, hallitusjuust, suitsujuust, kitsejuust, mozzarella.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('mitte üle 2,5% rasvasisaldusega maitsestamata jogurt', 200, 'g', 9, 'Ülejäänud piimatoodete portsjonid tuleks valida eelistatult siit grupist. Eelistage igast alagrupist madalama rasvasusega tooteid, kuid mitte päris lahjasid. Juustude hulku kuuluvad ka toorjuust, sulatatud juust, hallitusjuust, suitsujuust, kitsejuust, mozzarella.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('2,51 kuni 6% rasvasisaldusega maitsestamata jogurt', 150, 'g', 9, 'Ülejäänud piimatoodete portsjonid tuleks valida eelistatult siit grupist. Eelistage igast alagrupist madalama rasvasusega tooteid, kuid mitte päris lahjasid. Juustude hulku kuuluvad ka toorjuust, sulatatud juust, hallitusjuust, suitsujuust, kitsejuust, mozzarella.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuni 9,9% (k.a.) rasvasisaldusega juust', 90, 'g', 10, 'Ülejäänud piimatoodete portsjonid tuleks valida eelistatult siit grupist. Eelistage igast alagrupist madalama rasvasusega tooteid, kuid mitte päris lahjasid. Juustude hulku kuuluvad ka toorjuust, sulatatud juust, hallitusjuust, suitsujuust, kitsejuust, mozzarella.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('10–20,9% rasvasisaldusega juust', 50, 'g', 10, 'Ülejäänud piimatoodete portsjonid tuleks valida eelistatult siit grupist. Eelistage igast alagrupist madalama rasvasusega tooteid, kuid mitte päris lahjasid. Juustude hulku kuuluvad ka toorjuust, sulatatud juust, hallitusjuust, suitsujuust, kitsejuust, mozzarella.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('21–29,9% rasvasisaldusega juust', 35, 'g', 10, 'Ülejäänud piimatoodete portsjonid tuleks valida eelistatult siit grupist. Eelistage igast alagrupist madalama rasvasusega tooteid, kuid mitte päris lahjasid. Juustude hulku kuuluvad ka toorjuust, sulatatud juust, hallitusjuust, suitsujuust, kitsejuust, mozzarella.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('alates 30% rasvasisaldusega juust', 25, 'g', 10, 'Ülejäänud piimatoodete portsjonid tuleks valida eelistatult siit grupist. Eelistage igast alagrupist madalama rasvasusega tooteid, kuid mitte päris lahjasid. Juustude hulku kuuluvad ka toorjuust, sulatatud juust, hallitusjuust, suitsujuust, kitsejuust, mozzarella.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('hapu- ja rõõsk koor, 10% rasvasisaldusega (sh maitsestamata jogurt, 6,1–10% rasvasisaldusega)', 100, 'g', 11, 'Süües toite siit grupist, eelistada võimalikult madala rasvasusega');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('hapukoor, 20% rasvasisaldusega', 50, 'g', 11, 'Süües toite siit grupist, eelistada võimalikult madala rasvasusega');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('hapukoor, 30% rasvasisaldusega', 35, 'g', 11, 'Süües toite siit grupist, eelistada võimalikult madala rasvasusega');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('hapu- ja vahukoor, 30% ja kõrgema rasvasisaldusega', 30, 'g', 11, 'Süües toite siit grupist, eelistada võimalikult madala rasvasusega');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('maitsestatud jogurt, mitte üle 2,5% rasvasisaldusega', 140, 'g', 12, 'Selles grupis olevaid tooteid süüa võimalikult harva. 100g söödud toote kohta arvestada juurde ca 10 g (2 tl) ehk 1 portsjoni suhkrut');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('maitsestatud jogurt, üle 2,5% rasvasisaldusega', 100, 'g', 12, 'Selles grupis olevaid tooteid süüa võimalikult harva. 100g söödud toote kohta arvestada juurde ca 10 g (2 tl) ehk 1 portsjoni suhkrut');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('maitsestatud kohupiima(kreeme) või kodujuustu kuni 2,5% rasvasisaldusega', 100, 'g', 12, 'Selles grupis olevaid tooteid süüa võimalikult harva. 100g söödud toote kohta arvestada juurde ca 10 g (2 tl) ehk 1 portsjoni suhkrut');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('maitsestatud kohupiima(kreeme) või kodujuustu üle 2,5% rasvasisaldusega', 75, 'g', 12, 'Selles grupis olevaid tooteid süüa võimalikult harva. 100g söödud toote kohta arvestada juurde ca 10 g (2 tl) ehk 1 portsjoni suhkrut');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud lahja kala (nt haug, koha, heik, luts, mintai, ahven, merlang, tursk, saida, tilaapia)', 75, 'g', 13, 'Kogus käib puhastatud kala kohta. Praadimisel arvestada juurde rasv (5 g ehk 1 tl võid või õli on 1 portsjon lisatavaid rasvu)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud keskmise rasvasisaldusega kala (nt lest, rääbis, meriforell, siig, latikas)', 60, 'g', 13, 'Kogus käib puhastatud kala kohta. Praadimisel arvestada juurde rasv (5 g ehk 1 tl võid või õli on 1 portsjon lisatavaid rasvu)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud rasvast kala (nt räim, panga, vikerforell, heeringas)', 35, 'g', 13, 'Kogus käib puhastatud kala kohta. Praadimisel arvestada juurde rasv (5 g ehk 1 tl võid või õli on 1 portsjon lisatavaid rasvu)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud väga rasvast kala (nt skumbria, lõhe, angerjas)', 3, 'g', 13, 'Kogus käib puhastatud kala kohta. Praadimisel arvestada juurde rasv (5 g ehk 1 tl võid või õli on 1 portsjon lisatavaid rasvu)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('makra', 80, 'g', 13, 'Kalatoodetele eelistada tavalist kuumtöödeldud kala, kuna kalatooted on enamaltjaolt väga soolarikkad. Kalapulkade puhul eelistada suurema kalasisaldusega tooteid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('suitsu- ja soolakala', 50, 'g', 13, 'Kalatoodetele eelistada tavalist kuumtöödeldud kala, kuna kalatooted on enamaltjaolt väga soolarikkad. Kalapulkade puhul eelistada suurema kalasisaldusega tooteid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kalakonserv vees, tomatis või omas mahlas', 40, 'g', 13, 'Kalatoodetele eelistada tavalist kuumtöödeldud kala, kuna kalatooted on enamaltjaolt väga soolarikkad. Kalapulkade puhul eelistada suurema kalasisaldusega tooteid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kalapulgad', 40, 'g', 13, 'Kalatoodetele eelistada tavalist kuumtöödeldud kala, kuna kalatooted on enamaltjaolt väga soolarikkad. Kalapulkade puhul eelistada suurema kalasisaldusega tooteid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('vürtsikilu', 35, 'g', 13, 'Kalatoodetele eelistada tavalist kuumtöödeldud kala, kuna kalatooted on enamaltjaolt väga soolarikkad. Kalapulkade puhul eelistada suurema kalasisaldusega tooteid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kalakonserv õlis', 30, 'g', 13, 'Kalatoodetele eelistada tavalist kuumtöödeldud kala, kuna kalatooted on enamaltjaolt väga soolarikkad. Kalapulkade puhul eelistada suurema kalasisaldusega tooteid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('soolaheeringas', 30, 'g', 13, 'Kalatoodetele eelistada tavalist kuumtöödeldud kala, kuna kalatooted on enamaltjaolt väga soolarikkad. Kalapulkade puhul eelistada suurema kalasisaldusega tooteid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud kanafilee', 60, 'g', 14, 'Eelistada nahata linnuliha. Praadimisel arvestada juurde rasv (1 tl võid või õli on 1 portsjon lisatavaid rasvu)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud nahata kana-, kalkuni- ja pardiliha', 50, 'g', 14, 'Eelistada nahata linnuliha. Praadimisel arvestada juurde rasv (1 tl võid või õli on 1 portsjon lisatavaid rasvu)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud nahata haneliha', 40, 'g', 14, 'Eelistada nahata linnuliha. Praadimisel arvestada juurde rasv (1 tl võid või õli on 1 portsjon lisatavaid rasvu)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud nahaga kanaliha', 25, 'g', 14, 'Eelistada nahata linnuliha. Praadimisel arvestada juurde rasv (1 tl võid või õli on 1 portsjon lisatavaid rasvu)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud nahaga hane- ja pardiliha', 15, 'g', 14, 'Eelistada nahata linnuliha. Praadimisel arvestada juurde rasv (1 tl võid või õli on 1 portsjon lisatavaid rasvu)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud broilerimaks', 50, 'g', 14, 'Eelistada nahata linnuliha. Praadimisel arvestada juurde rasv (1 tl võid või õli on 1 portsjon lisatavaid rasvu)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kanasült', 120, 'g', 15, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud linnuliha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud linnuliha). Kui tarvitada tooteid siit grupist, eelistada suurema lihasisaldusega ja väiksema rasva- ja/või soolasisaldusega tooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kana- või kalkunisink', 80, 'g', 15, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud linnuliha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud linnuliha). Kui tarvitada tooteid siit grupist, eelistada suurema lihasisaldusega ja väiksema rasva- ja/või soolasisaldusega tooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kanaviinerid, kuni 5% rasvasisaldusega', 70, 'g', 15, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud linnuliha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud linnuliha). Kui tarvitada tooteid siit grupist, eelistada suurema lihasisaldusega ja väiksema rasva- ja/või soolasisaldusega tooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kanafrikadellid', 60, 'g', 15, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud linnuliha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud linnuliha). Kui tarvitada tooteid siit grupist, eelistada suurema lihasisaldusega ja väiksema rasva- ja/või soolasisaldusega tooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keeduvorst kanalihast', 50, 'g', 15, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud linnuliha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud linnuliha). Kui tarvitada tooteid siit grupist, eelistada suurema lihasisaldusega ja väiksema rasva- ja/või soolasisaldusega tooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('suitsutatud kalkuni või broiler', 50, 'g', 15, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud linnuliha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud linnuliha). Kui tarvitada tooteid siit grupist, eelistada suurema lihasisaldusega ja väiksema rasva- ja/või soolasisaldusega tooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kanalihast grill- ja ðaðlõkivorst', 40, 'g', 15, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud linnuliha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud linnuliha). Kui tarvitada tooteid siit grupist, eelistada suurema lihasisaldusega ja väiksema rasva- ja/või soolasisaldusega tooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kanasigar', 40, 'g', 15, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud linnuliha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud linnuliha). Kui tarvitada tooteid siit grupist, eelistada suurema lihasisaldusega ja väiksema rasva- ja/või soolasisaldusega tooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kanapihvid', 40, 'g', 15, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud linnuliha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud linnuliha). Kui tarvitada tooteid siit grupist, eelistada suurema lihasisaldusega ja väiksema rasva- ja/või soolasisaldusega tooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kanaviinerid üle 15% rasvasisaldusega', 40, 'g', 15, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud linnuliha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud linnuliha). Kui tarvitada tooteid siit grupist, eelistada suurema lihasisaldusega ja väiksema rasva- ja/või soolasisaldusega tooteid');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kananagitsad', 30, 'g', 15, 'Neid tooteid tuleks pigem vältida');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kanalihast suitsuvorst', 30, 'g', 15, 'Neid tooteid tuleks pigem vältida');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kiievi kotlett', 30, 'g', 15, 'Neid tooteid tuleks pigem vältida');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuivatatud kanasingi viilud', 20, 'g', 15, 'Neid tooteid tuleks pigem vältida');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud sea-, veise-, lamba- või vasikaliha', 35, 'g', 16, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Eelistada taist liha. Eelistada lahjemat hakkliha ning hakklihast (mitte hakklihasegust) ise valmistatud tooteid valmistoodetele. Praadimisel arvestada juurde rasv (1 tl võid või õli on 1 portsjon lisatavaid rasvu). ');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud hakkliha, kotlette, pihve, frikadelle vm', 30, 'g', 16, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Eelistada taist liha. Eelistada lahjemat hakkliha ning hakklihast (mitte hakklihasegust) ise valmistatud tooteid valmistoodetele. Praadimisel arvestada juurde rasv (1 tl võid või õli on 1 portsjon lisatavaid rasvu). ');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud põdra- või põhjapõdraliha', 50, 'g', 16, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi.  Praadimisel arvestada juurde rasv (1 tl võid või õli on 1 portsjon lisatavaid rasvu).');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud jänese- või metssealiha', 40, 'g', 16, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi.  Praadimisel arvestada juurde rasv (1 tl võid või õli on 1 portsjon lisatavaid rasvu).');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('sink ', 50, 'g', 17, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud liha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud (linnu)liha). Siit grupist valikut tehes eelistada tooteid, mille lihasisaldus on suurem ja rasva- ja/või soolasisaldus väiksem');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keeduvorst ', 30, 'g', 17, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud liha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud (linnu)liha). Siit grupist valikut tehes eelistada tooteid, mille lihasisaldus on suurem ja rasva- ja/või soolasisaldus väiksem');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('viinerid', 30, 'g', 17, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud liha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud (linnu)liha). Siit grupist valikut tehes eelistada tooteid, mille lihasisaldus on suurem ja rasva- ja/või soolasisaldus väiksem');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('sardellid', 30, 'g', 17, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud liha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud (linnu)liha). Siit grupist valikut tehes eelistada tooteid, mille lihasisaldus on suurem ja rasva- ja/või soolasisaldus väiksem');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('grillvorst', 30, 'g', 17, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud liha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud (linnu)liha). Siit grupist valikut tehes eelistada tooteid, mille lihasisaldus on suurem ja rasva- ja/või soolasisaldus väiksem');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('sinkvorst', 30, 'g', 17, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud liha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud (linnu)liha). Siit grupist valikut tehes eelistada tooteid, mille lihasisaldus on suurem ja rasva- ja/või soolasisaldus väiksem');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('lihakonserv', 30, 'g', 17, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud liha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud (linnu)liha). Siit grupist valikut tehes eelistada tooteid, mille lihasisaldus on suurem ja rasva- ja/või soolasisaldus väiksem');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('suitsuvorst', 20, 'g', 17, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud liha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud (linnu)liha). Siit grupist valikut tehes eelistada tooteid, mille lihasisaldus on suurem ja rasva- ja/või soolasisaldus väiksem');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('salaami', 20, 'g', 17, 'Selles grupis olevaid tooteid võib tarvitada kuumtöödeldud liha asemel, kuid teha seda harva (eelistada tavalist kuumtöödeldud (linnu)liha). Siit grupist valikut tehes eelistada tooteid, mille lihasisaldus on suurem ja rasva- ja/või soolasisaldus väiksem');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuni 5% rasvasusega sült', 100, 'g', 18, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Maksa ja maksast valmistatud toite võiks süüa kuni kord nädalas. Praadimisel arvestada juurde rasv (1tl võid või õli on 1 portsjon lisatavaid rasvu). Peekoni ja süldi puhul tuleb arvestada, et võrreldes tavalise liha ja teiste rupskitega on need toitainete sisalduselt oluliselt vähemväärtuslikumad');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('5,1-10% rasvasusega sült', 70, 'g', 18, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Maksa ja maksast valmistatud toite võiks süüa kuni kord nädalas. Praadimisel arvestada juurde rasv (1tl võid või õli on 1 portsjon lisatavaid rasvu). Peekoni ja süldi puhul tuleb arvestada, et võrreldes tavalise liha ja teiste rupskitega on need toitainete sisalduselt oluliselt vähemväärtuslikumad');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('üle 10%lise rasvasusega sült', 40, 'g', 18, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Maksa ja maksast valmistatud toite võiks süüa kuni kord nädalas. Praadimisel arvestada juurde rasv (1tl võid või õli on 1 portsjon lisatavaid rasvu). Peekoni ja süldi puhul tuleb arvestada, et võrreldes tavalise liha ja teiste rupskitega on need toitainete sisalduselt oluliselt vähemväärtuslikumad');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuumtöödeldud maks, neerud ', 45, 'g', 18, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Maksa ja maksast valmistatud toite võiks süüa kuni kord nädalas. Praadimisel arvestada juurde rasv (1tl võid või õli on 1 portsjon lisatavaid rasvu). Peekoni ja süldi puhul tuleb arvestada, et võrreldes tavalise liha ja teiste rupskitega on need toitainete sisalduselt oluliselt vähemväärtuslikumad');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('verivorst', 40, 'g', 18, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Maksa ja maksast valmistatud toite võiks süüa kuni kord nädalas. Praadimisel arvestada juurde rasv (1tl võid või õli on 1 portsjon lisatavaid rasvu). Peekoni ja süldi puhul tuleb arvestada, et võrreldes tavalise liha ja teiste rupskitega on need toitainete sisalduselt oluliselt vähemväärtuslikumad');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('verikäkk', 40, 'g', 18, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Maksa ja maksast valmistatud toite võiks süüa kuni kord nädalas. Praadimisel arvestada juurde rasv (1tl võid või õli on 1 portsjon lisatavaid rasvu). Peekoni ja süldi puhul tuleb arvestada, et võrreldes tavalise liha ja teiste rupskitega on need toitainete sisalduselt oluliselt vähemväärtuslikumad');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keedetud veisekeel', 30, 'g', 18, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Maksa ja maksast valmistatud toite võiks süüa kuni kord nädalas. Praadimisel arvestada juurde rasv (1tl võid või õli on 1 portsjon lisatavaid rasvu). Peekoni ja süldi puhul tuleb arvestada, et võrreldes tavalise liha ja teiste rupskitega on need toitainete sisalduselt oluliselt vähemväärtuslikumad');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('suitsupeekon', 25, 'g', 18, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Maksa ja maksast valmistatud toite võiks süüa kuni kord nädalas. Praadimisel arvestada juurde rasv (1tl võid või õli on 1 portsjon lisatavaid rasvu). Peekoni ja süldi puhul tuleb arvestada, et võrreldes tavalise liha ja teiste rupskitega on need toitainete sisalduselt oluliselt vähemväärtuslikumad');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('praetud peekon', 10, 'g', 18, 'Üks tikutoosisuurune tükk kaalub umbes 25-30 grammi. Maksa ja maksast valmistatud toite võiks süüa kuni kord nädalas. Praadimisel arvestada juurde rasv (1tl võid või õli on 1 portsjon lisatavaid rasvu). Peekoni ja süldi puhul tuleb arvestada, et võrreldes tavalise liha ja teiste rupskitega on need toitainete sisalduselt oluliselt vähemväärtuslikumad');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keedetud muna ', 1, 'tk', 19, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('keedetud vutimuna ', 5, 'tk', 19, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('praetud muna ', 1, 'tk', 19, 'Arvestada lisaks juurde ca 5 g (1 tl) õli ehk umbes 1 portsjon');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('omlett', 50, 'g', 19, 'Arvestada lisaks juurde 5 g õli (1 tl) ehk umbes 1 portsjon (vajadusel ka piim ja omletis olevad lisandid nagu juust, vorst, köögiviljad vm)');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('seemned', 10, 'g', 20, 'Varieeri. Tarbi igapäevaselt erinevaid seemneid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('pähklid ', 10, 'g', 20, 'Varieeri. Tarbi igapäevaselt erinevaid seemneid.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('oliivid õlis ', 15, 'g', 21, 'Oliivide kogused on antud puhastatud, kivideta koguste kohta.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('oliivid soolvees ', 40, 'g', 21, 'Oliivide kogused on antud puhastatud, kivideta koguste kohta.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('avokaado', 25, 'g', 21, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('õli ', 5, 'g', 22, 'Siit grupist eelistada õli ja võid. Praadimisel eelista rafineeritud õli, sea-, kookos- või palmirasva.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('või', 5, 'g', 22, 'Siit grupist eelistada õli ja võid. Praadimisel eelista rafineeritud õli, sea-, kookos- või palmirasva.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('margariin ja rasvavõie, üle 50% rasvasisaldusega ', 5, 'g', 22, 'Siit grupist eelistada õli ja võid. Praadimisel eelista rafineeritud õli, sea-, kookos- või palmirasva.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('margariin ja rasvavõie, kuni 50% rasvasisaldusega ', 15, 'g', 22, 'Siit grupist eelistada õli ja võid. Praadimisel eelista rafineeritud õli, sea-, kookos- või palmirasva.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kookosrasv ', 5, 'g', 22, 'Siit grupist eelistada õli ja võid. Praadimisel eelista rafineeritud õli, sea-, kookos- või palmirasva.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('searasv, -pekk ', 5, 'g', 22, 'Siit grupist eelistada õli ja võid. Praadimisel eelista rafineeritud õli, sea-, kookos- või palmirasva.');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('suhkur', 10, 'g', 23, 'Eelista suurema kakaosisaldusega ðokolaadi');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('mesi', 10, 'g', 23, 'Eelista suurema kakaosisaldusega ðokolaadi');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('moos', 20, 'g', 23, 'Eelista suurema kakaosisaldusega ðokolaadi');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('ðokolaad', 10, 'g', 23, 'Eelista suurema kakaosisaldusega ðokolaadi');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('ðokolaadikommid', 10, 'g', 23, 'Eelista suurema kakaosisaldusega ðokolaadi');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('muud kompvekid', 10, 'g', 23, 'Eelista suurema kakaosisaldusega ðokolaadi');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('nektarit, karastus-, mahla-, kalja-, energiajooke, morssi, jääteed, maitsevett', 100, 'g', 24, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('mahla-, marja- ja puuviljakissell', 60, 'g', 24, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kartuli- ja maisikrõpsud', 10, 'g', 25, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('popkorn', 10, 'g', 25, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('küüslaugu-, maitsestatud näkileivad, soolapähklid', 10, 'g', 25, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kuivikud, soolased küpsised', 10, 'g', 25, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kakao- ja pähklivõi, 75% rasvasusega', 10, 'g', 25, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('pannkoogid', 20, 'g', 26, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('pärmitaignast saiakesed-pirukad, rullbiskviit, vahukoorekuklid ja -tort, sotðnikud, mee- ja kräsupeakook', 15, 'g', 26, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('muffin, keeks, kringel, lehttaignapirukad, liiva- ja muretaigna koogid, ðokolaadikook, moosipallid, pontðikud, rummikook, Napoleoni kook', 10, 'g', 26, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('magusad küpsised, vahvlid', 10, 'g', 26, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('puding, jäätisekokteil', 30, 'g', 27, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('piima- ja jogurtijäätis ', 25, 'g', 27, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('koorejäätis', 20, 'g', 27, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kohuke', 15, 'g', 27, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('jäätis ðokolaadiglasuuriga', 10, 'g', 27, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('suhkruga kondenspiim', 10, 'g', 27, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('sorbettjäätis', 35, 'g', 28, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('ðokolaadi- ja karamellkastmed ', 15, 'g', 28, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('kirju koer, iirise- maisipulgamagustoit, sefiir, besee, halvaa, pastilaad, martsipan, rosinad ðokolaadis jms', 10, 'g', 28, '0');
insert into toidupyramiid.products(name, unitVal, unitType, prodType, comment) values('ðokolaadivõi', 10, 'g', 28, '0');

--söögid
insert into toidupyramiid.events(userID, productID, amount, eventDay) values(1, 7, 2, 1)
insert into toidupyramiid.events(userID, productID, amount, eventDay) values(1, 105, 2, 1)
insert into toidupyramiid.events(userID, productID, amount, eventDay) values(1, 125, 2, 1)
insert into toidupyramiid.events(userID, productID, amount, eventDay) values(1, 150, 3, 1)
insert into toidupyramiid.events(userID, productID, amount, eventDay) values(1, 131, 1, 1)



--rollid
insert into toidupyramiid.userRoles(userID, roleID) values(1, 2);
insert into toidupyramiid.userRoles(userID, roleID) values(1, 1);
insert into toidupyramiid.userRoles(userID, roleID) values(2, 1);
insert into toidupyramiid.userRoles(userID, roleID) values(3, 1);
insert into toidupyramiid.userRoles(userID, roleID) values(4, 2);

insert into toidupyramiid.userRelationships(customerUserID, consultantUserID) values(2, 1);
insert into toidupyramiid.userRelationships(customerUserID, consultantUserID) values(1, 4);
insert into toidupyramiid.userRelationships(customerUserID, consultantUserID) values(3, 1);

